### ISSUE TITLE
Setting key "net.ipv6.conf.default.forwarding": Read-only file system

### ISSUE THREAD

**Issue by orangeudav** [kylemanna/docker-openvpn#56]
After running this
```
docker run --volumes-from $OVPN_DATA -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
```
i got this error in docker logs 
```
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
Enabling IPv6 Forwarding
sysctl: setting key "net.ipv6.conf.default.forwarding": Read-only file system
```
I using DigitalOcean's Ubuntu 14.04 LTS
```
ufw default allow
```
Enable this settings in /etc/ufw/sysctl.conf does nothing change
```
net/ipv4/ip_forward=1
net/ipv6/conf/default/forwarding=1
net/ipv6/conf/all/forwarding=1
```

**Comment by kylemanna** [comment]
Sorry about that, broke it when I merged IPv6 support. Try doing a docker pull on the image and try it again.

**Comment by kylemanna** [comment]
Out of curiosity did you get it working?

**Comment by orangeudav** [comment]
Yep! After second try, all working perfect! Thank you very much!

**Comment by kylemanna** [comment]
Yeah, that was my fault.  Sounds like you hit an edge case with IPv6 enabled that I didn't test for. Oops.  Glad it's working. :smile:

**Comment by phlegx** [comment]
I'm getting pretty much the same error with the latest ```docker-openvpn``` on ```Ubuntu 16.04 LTS```

```
 docker-compose up
Recreating openvpn_openvpn_1
Attaching to openvpn_openvpn_1
openvpn_1  | Enabling IPv6 Forwarding
openvpn_1  | Failed to enable IPv6 Forwarding default
openvpn_1  | Failed to enable IPv6 Forwarding
openvpn_1  | iptables: No chain/target/match by that name.
openvpn_1  | iptables: No chain/target/match by that name.
openvpn_1  | sysctl: error setting key 'net.ipv6.conf.default.forwarding': Read-only file system
openvpn_1  | sysctl: error setting key 'net.ipv6.conf.all.forwarding': Read-only file system
openvpn_1  | Fri May 20 13:01:35 2016 RESOLVE: Cannot parse IP address: server
openvpn_1  | Options error: error parsing --server parameters
openvpn_1  | Use --help for more information.
openvpn_openvpn_1 exited with code 1
```

Maybe something has changed with the new Ubuntu version? Or is it maybe my fault that this happens?

**Comment by phlegx** [comment]
A ```privileged: true``` solved at least the "Read only" problem. The error that still persists is:

```   
openvpn_1  | Fri May 20 13:01:35 2016 RESOLVE: Cannot parse IP address: server
openvpn_1  | Options error: error parsing --server parameters
```

Not sure what this is about?

**Comment by ragaar** [comment]
@kylemanna is there a clean way to disable IPv6 Forwarding, to remove the warnings?

As for the necrotic post:
I'm opening the conversation on this issue because it is the first hit on Google.

**Comment by ragaar** [comment]
Resolved the issue: Found the IPv6 conditional-statement in ovpn_run.
Solution: Disable IPv6 on the host.

REF: http://www.techrepublic.com/article/how-to-disable-ipv6-on-linux/

**Comment by r3lik** [comment]
how can I run `ipv6` without privileged mode having to be enabled? Running 2.4+.

**Comment by mathieu-aubin** [comment]
according to new stndards, ipv6 is the default protocol that is used in most recent linux distributions.

If /etc/gai.conf exists, it could mean that its been modified to give precence to ipv4 and could be why ipv4 is used. It could also be for a huge amount of other network related configs, too. google for it or show us/me its content if you wanted to make sure. It shouldnt contain sensitive informations but make sure you anonymize them before doing so.

Firewall configs could also prevent  ipv6 from being used under certain conditions. ´sudo ip6tables -S’ would show you the configs.

and oh, yes... the sysctl configs for ipv6 must allow for it, too.

if you have no access to the server as root, there is almost no chances you can control networking behaviors.

note: i replied quickly without really being aware of the whole discussion so please forgive me if i am way out of context.

**Comment by utdrmac** [comment]
still an issue, april 2019. how do you fix the read-only errors?

```
# docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
fb5ce10241c2efa3bef874abb2717d0c68c00420f4b0f1256f23ee7914157c3e
root@blacklion:/etc/openvpn#
root@blacklion:/etc/openvpn# docker logs fb5
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
Enabling IPv6 Forwarding
sysctl: error setting key 'net.ipv6.conf.all.disable_ipv6': Read-only file system
Failed to enable IPv6 support
sysctl: error setting key 'net.ipv6.conf.default.forwarding': Read-only file system
Failed to enable IPv6 Forwarding default
sysctl: error setting key 'net.ipv6.conf.all.forwarding': Read-only file system
Failed to enable IPv6 Forwarding
Running 'openvpn --config /etc/openvpn/openvpn.conf --client-config-dir /etc/openvpn/ccd --crl-verify /etc/openvpn/crl.pem '
```

**Comment by mathieu-aubin** [comment]
@utdrmac read this https://github.com/kylemanna/docker-openvpn/issues/56#issuecomment-418587287

``` 
# If this fails, ensure the docker container is run with --privileged […]
```
